<?php

$url1 = $this->url (array('controller' => 'account', 'action' => 'edit',
        'id_account' => $this->account->get_id ()), null, true );

$url2 = $this->url (array('controller' => 'account', 'action' => 'delete',
        'id_account' => $this->account->get_id ()), null, true );

print <<<__TEXT__
Really delete this account?

<a href="$url1" data-role="button" target="_top">No</a>
<a href="$url2" data-role="button">Yes</a>
__TEXT__;

?>
