<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<?php
echo $this->headTitle();
?>

<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
<script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
</head>

<body>

<?php
$title = $this->title;
if ($this->title == '')
{
    $title = 'cookingwithgas';
}
?>

<div data-role="page">
<div data-role="header"><h1><?= $title ?></h1></div>
<div data-role="content">

<?php 
$config = Zend_Registry::get('config');
$footer_url = $config->base_url;
echo $this->layout()->content;
?>

</div>

<div data-role="footer" data-id="recipefooter" data-position="fixed">
    <a href="<?= $footer_url ?>" data-role="button" rel="external">Home</a>
</div>

</body>
</html>
